image_dir = "/data/ukbiobank/blobs/fundus/data/"
results_dir = "/data/yue/automorph_azure/results/results/"
worker = 0
sample_num = False #Put False if you do not want to sample
device = "cuda" #can specify cuda:0  or cuda or CPU
batch_size = 2  
sparse=True
ukb=True
debug=False
quality_thresh = 'good' # options are "good", "usable", "all" to use for thresholding the quality
