#image_dir = "/data/ukbiobank/blobs/fundus/data/"
#results_dir = "/data/yue/automorph_azure/results/results/"
image_dir = '/data/anand/Automorph_data/test/images/'
results_dir = '/data/anand/Automorph_data/test/results/'
worker = 0
sample_num = False #Put False if you do not want to sample
device = "cuda" #can specify cuda:0  or cuda or CPU
batch_size = 4  
sparse=True
ukb=True
debug=False
quality_thresh = 'good' # options are "good", "usable", "all" to use for thresholding the quality
